### ISSUE TITLE
'PyContainer' object has no attribute 'predict_proba'

### ISSUE THREAD

**Issue by amjltc295** [MichaelHills/seizure-detection#1]
I tried to run the code, training is ok, but predict.py doesn't work.
I read the hickle.py and checked the container_type inside the classifier, it's "sklearn.ensemble.forest.RandomForestClassifier".
I guess it has the right thing inside the pycontainer, but I cannot figure out why predict_proba is not working.

Traceback (most recent call last):
  File "./predict.py", line 6, in <module>
    run_seizure_detection('make_predictions')
  File "seizure_detection.py", line 179, in run_seizure_detection
    train_full_model(make_predictions=True)
  File "seizure_detection.py", line 114, in train_full_model
    predictions = MakePredictionsTask(task_core).run()
  File "seizure/tasks.py", line 25, in run
    return self.task_core.cached_data_loader.load(self.filename(), self.load_data)
  File "common/data.py", line 42, in load
    data = func()
  File "seizure/tasks.py", line 121, in load_data
    return make_predictions(self.task_core.target, X_test, y_classes, classifier_data)
  File "seizure/tasks.py", line 442, in make_predictions
    predictions_proba = classifier.predict_proba(X_test)
AttributeError: 'PyContainer' object has no attribute 'predict_proba'

ipdb> pp classifier.container_type
class 'sklearn.ensemble.forest.RandomForestClassifier'>"
ipdb> pp type(classifier[0])
type 'numpy.ndarray'>
ipdb> pp type(classifier)
class 'hickle.PyContainer'>

**Comment by MichaelHills** [comment]
Sorry this was a long time ago before I learnt about virtualenv and better ways to handle dependency management in Python. I think I might have been using hickle 0.1 at that time? It's possible that the hickle library has changed to be no longer compatible with the way I was using it.

**Comment by MichaelHills** [comment]
Sorry probably 1.5 years too late. I've updated the repo with a `requirements.txt` and fixed this issue. 

The problem was that `hickle` used to fail to serialize scikit classifiers, but in newer versions it would succeed (to a degree). My code relied on it failing to fallback to `pickle`. I stuck in a hack to ensure classifiers are pickled and not hickled and it works again.
